import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
	subsets: ["latin"],
	display: "swap",
	weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
	title: "Portfolio - Wiktor Gabryszak",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${nunito.className} bg-zinc-950`}>
				<div className='flex min-h-screen w-auto'>
					<div className='flex lg:max-h-[1000px] lg:min-h-[900px] items-center gap-5 lg:p-8 p-4'>{children}</div>
				</div>
			</body>
		</html>
	);
}
