import "./globals.css";

export const metadata = {
	title: "Portfolio - Wiktor Gabryszak",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={` antialiased`}>{children}</body>
		</html>
	);
}
